Criado Workflow para verificação do padrão de snake_case nos arquivos
guiaanonima/InfoSecTools pull request #18
Opened 2024-01-17 00:23 UTC by johwconst

- Adicionado script bash para verificação dos arquivos .py

2024-01-17 23:54 UTC, stephan-lopes requested changes

2024-01-17 23:54 UTC, stephan-lopes commented on .github/workflows/check_snake_case.yml
> +                  echo "::error title=Contem arquivos fora do padrao snake_case::O Arquivo $file_name esta fora do padrao"
Modifica só nessa linha o `$file_name` por `$files`. Assim, ele mostra o arquivo com a extensão, e o diretório de forma correta.

2024-01-17 23:54 UTC, stephan-lopes commented on .github/workflows/check_snake_case.yml
> +                  echo "::error title=Contem arquivos fora do padrao snake_case::O Arquivo $file_name esta fora do padrao"
No caso, na linha 18

2024-01-17 23:56 UTC, stephan-lopes commented on .github/workflows/check_snake_case.yml
> +                  echo "::error title=Contem arquivos fora do padrao snake_case::O Arquivo $file_name esta fora do padrao"
Modifiquei para que possa já aprovar o PR

2024-01-17 23:57 UTC, stephan-lopes approved these changes
Muito bom!

2024-01-18 13:04 UTC, Dokaoista approved these changes

2024-01-18 13:16 UTC, merged