Checagem de SourceList e Correção de Bug
guiaanonima/InfoSecTools pull request #43
Opened 2024-01-30 14:16 UTC by Dokaoista

Neste PR, foram feitas as seguintes alterações:
- Adicionado a validação da existência do arquivo _infosectools.list_ na parte de instalação de pacotes;
- Corrigido o bug que se encontrava na parte de adicionar repositório, o qual se deve a somente a leitura sem checagem do arquivo _infosectools.list_.

2024-02-01 15:28 UTC, stephan-lopes requested changes

2024-02-01 15:28 UTC, stephan-lopes commented on instalacao.py
> +		with open('/etc/apt/sources.list.d/infosectools.list', 'r') as arquivo:
Dá uma olhada nesse carinha aqui: https://www.freecodecamp.org/news/how-to-check-if-a-file-exists-in-python/

Acho que dessa forma, fica melhor a checagem de existência de arquivos do que tentar abrir ele

2024-02-01 15:28 UTC, stephan-lopes commented on menu_subfunctions.py
> -    if repository not in lines:
Essa linha escreve o repositorio dentro do source list caso não exista o arquivo, ou caso essa linha não exista dentro do arquivo. Sendo assim, remover ela vai fazer com que não seja adicionada as linhas do repositório do kali.

2024-02-02 16:34 UTC, johwconst approved these changes

2024-02-04 18:49 UTC, Willianjesusdasilva approved these changes
mesmo com a pendencia da verificação, é o PR está valido.

2024-02-04 18:49 UTC, Willianjesusdasilva commented on instalacao.py
> +		if path.exists('/etc/apt/sources.list.d/infosectools.list'):
salve gatão.

No python, primeiro fazemos a tentativa e depois tratamos o erro.
Não é uma boa pratica em python fazer verificação antes de realizar uma ação dada a velocidade do intepretador.

2024-02-04 18:52 UTC, stephan-lopes approved these changes

2024-02-04 18:52 UTC, merged